token transfers, human readable logs, css fixes
telosnetwork/teloscan pull request #108
Opened 2022-08-18 10:08 UTC by tomtomcrypto

2022-08-22 01:43 UTC, donnyquixotic submitted a review, later dismissed

2022-08-22 01:43 UTC, donnyquixotic commented on src/components/AddressField.vue
> +        color: #666666
move color hex to  [global variables](https://github.com/telosnetwork/teloscan/blob/master/src/css/quasar.variables.sass) and reference as variable

2022-08-22 01:43 UTC, donnyquixotic commented on src/components/AddressField.vue
> +        color: #c3c3c3
move color hex to  [global variables](https://github.com/telosnetwork/teloscan/blob/master/src/css/quasar.variables.sass) and reference as variable

2022-08-22 01:43 UTC, donnyquixotic commented on src/components/Footer.vue
> +            style="font-size:15px;color:brown;padding-bottom:4px; margin-left: 3px;"
I'd move these rules to a scoped class

2022-09-12 21:46 UTC, EJSG commented
pushed some updates, still WIP. I'm not sure how to test the token transfers

2022-09-12 21:48 UTC, EJSG commented on src/components/Transaction/LogsTableRow.vue
> +                            {{ log.args[index] / (10 ** log.token.decimals) }}
precision not maintained here, move to a method w/ BigNumber arithmetic

2022-09-12 21:49 UTC, EJSG commented on src/components/Transaction/LogsTableRow.vue
> -            if(this.log.contract) return;
moved this logic to parent, it is illegal to modify a prop in Vue

2022-09-12 21:50 UTC, EJSG commented on package.json
> +    "vue-json-viewer": "3",
this was broken. v3 supports Vue 3

2022-09-13 12:15 UTC, tomtomcrypto commented
I had removed the contract icon on the transaction page as it clashes with the copy address button, seems it is back

2022-09-13 14:18 UTC, tomtomcrypto commented
There is something very wrong going on on testnet
https://testnet.teloscan.io/tx/0xbacfe143c2439acc5d891d4590d683e2235cfb394827eb17dc2f6bb94ab5fafc
this should be transfer, I simply sent some erc20 from metamask, instead it says join_tg_invmru_haha_fd06787

2022-09-13 14:48 UTC, tomtomcrypto commented
Ok so I think the transfer thing is do to this issue: https://github.com/telosnetwork/teloscan/issues/143

2022-09-14 01:14 UTC, EJSG requested changes

2022-09-14 01:14 UTC, EJSG commented on src/pages/Transaction.vue
> +<style lang="sass">
since these styles aren't namespaced, they need to be at least `scoped`. as written, these styles will "bleed"  

`<style scoped lang="sass">`

2022-09-14 18:50 UTC, EJSG approved these changes

2022-09-14 18:52 UTC, merged