145 stlos uat improvements and requests
telosnetwork/teloscan pull request #157
Opened 2022-09-21 00:34 UTC by EJSG

2022-09-21 18:20 UTC, donnyquixotic commented
@EJSG when merged, refer to https://github.com/telosnetwork/teloscan/pull/158

2022-09-21 18:24 UTC, donnyquixotic approved these changes

2022-09-22 08:46 UTC, Kersten-TCD requested changes
All changes working as expected and tested. Great job.

Please verify MetaMask integration, transaction window not brought to front for transactions. (Chrome, MAC)

2022-09-22 21:14 UTC, donnyquixotic approved these changes

2022-09-22 21:25 UTC, donnyquixotic commented
@tomtomcrypto can you confirm the respective contract addresses for testnet/mainnet?
testnet:
    STAKED_TLOS_CONTRACT_ADDRESS: '0xa9991E4daA44922D00a78B6D986cDf628d46C4DD',
    TELOS_ESCROW_CONTRACT_ADDRESS: '0x7E9cF9fBc881652B05BB8F26298fFAB538163b6f',
mainnet:   
    STLOS_CONTRACT_ADDRESS: '0xB4B01216a5Bc8F1C8A33CD990A1239030E60C905',
    STLOS_ESCROW_CONTRACT_ADDRESS: '0x95F5713A1422Aa3FBD3DCB8D553945C128ee3855',

2022-09-22 21:54 UTC, merged