sTLOS
telosnetwork/teloscan pull request #158
Opened 2022-09-21 18:18 UTC by donnyquixotic

When sTLOS updates are pushed to dev, remove draft status.

@Kersten-TCD @EJSG 
Here is the netlify instance that is the dev branch pointing to mainnet: https://dev-mainnet-teloscan.netlify.app/

2022-09-22 08:44 UTC, Kersten-TCD requested changes
Stage-Mainnet and Mainet deployments not working. All staking modals not loading.

2022-09-22 21:56 UTC, donnyquixotic commented
@Kersten-TCD use this link for testing: https://dev-mainnet-teloscan.netlify.app/

2022-09-22 23:17 UTC, EJSG approved these changes

2022-09-23 11:18 UTC, Kersten-TCD approved these changes
All functions are working as expected now, including MetaMask.

Please wait with merge until Monday 26. when native contracts have been deployed.

Great work, all!!!

2022-09-26 23:14 UTC, merged