added wei toggle for erc20 transaction list
telosnetwork/teloscan pull request #227
Opened 2022-11-07 10:55 UTC by tomtomcrypto

# Fixes #222 #220 #221 

## Description

Adding human-readable functionality to the internal transactions list and small display enhancements.

- [ ] Add toggleable log formatting to the internal transaction list
- [ ] Add wei toggle to ERC20 transaction list
- [ ] Add USD amount to transaction gas fee
- [ ] Format staking TVL value properly

## Test scenarios

- [ ] Users can navigate to the internal transaction tab of a transaction and toggle between human-readable mode or normal mode.
- [ ] Users can navigate to transaction general tab and toggle wei amount on the erc20 transaction list if there are any
- [ ] Users can navigate to transaction general tab and see how much the gas fee was in USD

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages

2022-11-07 20:58 UTC, donnyquixotic requested changes

2022-11-07 20:58 UTC, donnyquixotic commented on src/components/Transaction/InternalTxnsTable.vue
> +    },
remove empty `data()`

2022-11-07 22:23 UTC, tomtomcrypto commented
Tracking a bug this introduced on some logs

2022-11-09 13:06 UTC, tomtomcrypto commented
> > Tracking a bug this introduced on some logs, ie: https://deploy-preview-227--dev-mainnet-teloscan.netlify.app/tx/0x49780341cf3f7b71d85e02dfbc7d58933044a53e0e96dbc018297faf1b903301#eventlog
> 
> Fixed
> 
> Checking why order of internal transactions is messed up sometimes on navigation, should be good to review after that

Fixed in latest commit, good to review

2022-11-10 01:46 UTC, EJSG commented
Damn dude this PR is amazing, everything looks really good. Only comment is that the h3 for No logs / internal transactions looks kind of silly (really large) because our typography isnt set up yet. I suggest switching them to just use a `<p>`

e.g. https://deploy-preview-227--teloscan-stage.netlify.app/tx/0x80f0051d8782bb0be772eba5f0ca1a7bcbe84c4266e1b4e7f59b6cac5c5a2747#eventlog
and https://deploy-preview-227--dev-mainnet-teloscan.netlify.app/tx/0xe525d969b79e88c6147135a07737dfe6eaad74e6c967bd595aaa8d93ce201d03#eventlog
![image](https://user-images.githubusercontent.com/11837820/200980025-4365e013-a8c1-4c43-96cc-4805c32d9932.png)

2022-11-10 01:46 UTC, EJSG requested changes
just the one small comment. seriously amazing work killing so many issues with this

2022-11-10 12:30 UTC, tomtomcrypto commented
> just the one small comment. seriously amazing work killing so many issues with this

Yeah it is the same problem on the logs page actually, never got around to it, I'll change it.

2022-11-10 12:40 UTC, tomtomcrypto commented
Used an H5, size seems good and it is easier to align vertically

2022-11-11 21:30 UTC, donnyquixotic approved these changes

2022-11-11 21:31 UTC, merged