Added ERC1155, renamed claim to withdraw, show none on address page, ...
telosnetwork/teloscan pull request #241
Opened 2022-11-16 22:47 UTC by tomtomcrypto

# Fixes #183 #233 #238 

## Description

This adds ERC115 support to teloscan as well as various UI fixes & additions

## Test scenarios

- [ ] User should be able to see an ERC1155 transfer on the transaction page and in its log
- [ ] User should see an ERC1155 tab when navigating to the address page
- [ ] User should be able to navigate to the ERC1155 tab of the address page and see a list of all their ERC1155 transfers
- [ ] User should see a "Withdraw" tab instead of a "Claim" tab on the staking page
- [ ] All mention of claim should be replaced by withdraw in the "Claim" tab
- [ ] Claim component should be renamed to Withdraw
- [ ] User should be able to see the current nonce of an address on the address page

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages

2022-11-25 05:01 UTC, donnyquixotic requested changes

2022-11-25 05:01 UTC, donnyquixotic commented on src/components/TransferTable.vue
> +                            let tokenId = (this.tokenType === 'erc1155') ? BigNumber.from(log.data.substr(0, 66)).toString() : BigNumber.from(log.topics[3]).toString();
'magic numbers' that might benefit from being a descriptive const variable for readability

2022-11-28 19:30 UTC, EJSG commented on src/components/TransferTable.vue
> +                            to = `0x${log.topics[2].substring(log.topics[2].length - 40)}`;
this should do it (const name might not be perfect though):
```js
const getTopicHash = index => `0x${log.topics[index].substring(log.topics[index].length - 40)}`
```

2022-11-28 19:31 UTC, EJSG commented on src/components/TransferTable.vue
> +            // TODO: switch path according to ERC type (ERC20 & ERC721 have same sig)
TODO should reference a github issue or be resolved before PR is merged

2022-11-28 19:34 UTC, EJSG commented on src/lib/Contract.js
> +      if(parsedLog.name && parsedLog.eventFragment && parsedLog.eventFragment.inputs){
`parsedLog.eventFragment && parsedLog.eventFragment.inputs` can be simplified to `parsedLog.eventFragment?.inputs`

2022-11-28 19:35 UTC, EJSG commented on src/lib/ContractManager.js
> +        return (sig === '0xc3d58168') ? 'erc1155' : type;
constant for the signature would be nice for readability

2022-11-28 19:44 UTC, EJSG commented
looks great to me! just a few comments + what don said. also do you have an example of an address with `ERC1155` xfers I can test with?

2022-11-29 15:14 UTC, tomtomcrypto commented on src/components/Transaction/InternalTxns.vue
> +            name = (itx.type === 'create')  ? 'Contract deployment' : name;
It cannot be a const as this is the fallback, the name among other variable gets overriden later if we can parse with ABI

2022-12-01 02:18 UTC, donnyquixotic commented on src/components/Transaction/InternalTxns.vue
> +            name = (itx.type === 'create')  ? 'Contract deployment' : name;
that's fine.

2022-12-19 13:27 UTC, tomtomcrypto commented on src/components/Transaction/LogsViewer.vue
> +                type = (function_signature === '0xc3d58168') ? 'erc1155' : type;
now imported from utils

2022-12-20 17:30 UTC, EJSG approved these changes
:fire:

2022-12-23 00:41 UTC, Viterbo approved these changes

2022-12-27 13:30 UTC, merged