#107 | Page tabs and routing fix
telosnetwork/teloscan pull request #263
Opened 2022-12-22 20:53 UTC by EJSG

# Fixes #107

## Description
Route hashes, which are used by the quasar tabbing component, currently break if an invalid route is navigated to. This PR fixes how hashes are handled.

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages

2023-01-02 18:38 UTC, donnyquixotic requested changes

2023-01-02 18:38 UTC, donnyquixotic commented on src/pages/staking/Staking.vue
> +        $route: {
this is identical to the implementation in `Transaction.vue`, refactor if practical.

2023-01-02 18:38 UTC, donnyquixotic commented on src/pages/Transaction.vue
> +        $route: {
this is identical to the implementation in `Staking.vue`, refactor if practical.

2023-01-02 20:35 UTC, karynemayer approved these changes
I'm good to merge it once the refactor is in place

2023-01-03 21:37 UTC, EJSG commented
@donnyquixotic @karynemayer updated

2023-01-03 22:26 UTC, karynemayer approved these changes

2023-01-05 20:16 UTC, donnyquixotic submitted a review, later dismissed

2023-01-05 20:22 UTC, merged