Adding Portuguese (pt-BR) translation
telosnetwork/teloscan pull request #312
Opened 2023-01-17 14:51 UTC by Viterbo

# Fixes #298 

## Description
This PR is replacing the original PR created by 7glaucio which needed to be updated because of the last structural modifications. It is based on the last version of the English file (in file `src/i18n/en-us/index.js`.)

2023-01-17 15:05 UTC, Viterbo commented
This PR is blocked too until [PR292](https://github.com/telosnetwork/teloscan/pull/292) is actually merged.

2023-01-18 17:32 UTC, donnyquixotic approved these changes

2023-01-18 17:34 UTC, donnyquixotic approved these changes

2023-01-18 17:39 UTC, donnyquixotic approved these changes

2023-01-19 23:30 UTC, karynemayer requested changes
I left a few suggestions on wording that I thought it would make sense.

2023-01-19 23:30 UTC, karynemayer commented on src/i18n/pt-br/index.js
> +            str_input_hint: 'Aspas duplas em strings (sequência de textos) devem ser evitadas(\\")',
```suggestion
            str_input_hint: 'Aspas duplas em strings (sequência de caracteres) devem ser evitadas(\\")',
```

2023-01-19 23:30 UTC, karynemayer commented on src/i18n/pt-br/index.js
> +            block_height: 'Altura do bloqueio',
```suggestion
            block_height: 'Altura do bloco',
```

2023-01-19 23:30 UTC, karynemayer commented on src/i18n/pt-br/index.js
> +            search_placeholder: 'Endereço, Tx, Bloqueio',
```suggestion
            search_placeholder: 'Endereço, Tx, Bloco',
```

2023-01-21 16:14 UTC, Viterbo commented on src/i18n/pt-br/index.js
> +            note_unstaking_period: 'Lembre-se que há um período de retirada de {period}',
The period value comes from a call to this function which already manages translation:

https://github.com/telosnetwork/teloscan/blob/dev/src/pages/staking/staking-utils.js#L10-L32
```typescript
export function formatUnstakePeriod(seconds, $t) {
    if (seconds === null)
        return '--';

    let quantity;
    let unit;

    if (seconds < HOUR_SECONDS) {
        quantity = seconds / 60;
        unit = $t('pages.staking.minutes');
    } else if (seconds < DAY_SECONDS) {
        quantity = seconds / HOUR_SECONDS;
        unit = $t('pages.staking.hours');
    } else {
        quantity = seconds / DAY_SECONDS;
        unit = $t('pages.staking.days');
    }

    if (!Number.isInteger(quantity))
        quantity = quantity.toFixed(1);

    return `${quantity} ${unit}`;
}
```

2023-01-22 01:17 UTC, donnyquixotic approved these changes

2023-01-23 19:35 UTC, donnyquixotic submitted a review, later dismissed

2023-01-25 12:45 UTC, Viterbo commented on src/i18n/pt-br/index.js
> +        enable_wallet_extensions: 'Ative a extensão MetaMask e defina o padrão como `preferir extensões` nas configurações da carteira do navegador para usar a carteira MetaMask',
@karynemayer, these two lines were recently added in the [Brave native wallet PR](https://github.com/telosnetwork/teloscan/pull/314). 

Can you check them and suggest corrections if needed?

2023-01-25 22:54 UTC, karynemayer approved these changes

2023-01-25 22:58 UTC, donnyquixotic approved these changes

2023-01-25 22:58 UTC, merged