Remembering pagination state for tx table
telosnetwork/teloscan pull request #336
Opened 2023-01-26 14:42 UTC by Viterbo

# Fixes #293

## Description
When you find a special transaction from the table and you follow the link and then come back to the table, the pagination is lost and you must start from the first page again which leads to a terrible user experience.

This PR makes the table save in local storage the last pagination state and recovers it every time the table is used again.

## Test scenarios
To recreate this new behavior you must:
- go to the home page
- change the current page and the page size
- follow the link of any of the listed transaction
- press the Back button of your browser.
- the table should recover the last pagination state

## Checklist:
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2023-01-26 21:48 UTC, donnyquixotic requested changes
We should handle this in the router by incorporating query/filter params as part of routing (e.g.  `/<address>?page=3` )  for the appropriate pages to track pagination instead of using state. This would allow more depth of history tracking and avoid unintended behavior. For instance, If you navigate to a different page and click on an _address_ in the table, the page state is applied where it shouldn't be.

2023-01-26 21:48 UTC, donnyquixotic commented on src/components/TransactionTable.vue
> +            console.log('onRequest', props);
remove console log

2023-01-27 17:50 UTC, EJSG commented on src/components/TransactionTable.vue
> +        const paginationStaet = localStorage.getItem(STORAGE_KEY);
typo in variable name

2023-01-27 17:50 UTC, EJSG commented on src/components/TransactionTable.vue
> +            console.log('onRequest', props);
rm console log

2023-01-30 12:24 UTC, Viterbo commented on src/components/TransactionTable.vue
> +        const paginationStaet = localStorage.getItem(STORAGE_KEY);
This code is no longer present

2023-01-30 17:21 UTC, EJSG approved these changes
nice, this works great

2023-01-30 21:03 UTC, donnyquixotic approved these changes

2023-01-30 23:28 UTC, merged