release candidate
telosnetwork/teloscan pull request #345
Opened 2023-01-30 23:36 UTC by donnyquixotic

# Fixes #issue_number

## Description

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file
-   [ ] I have created a new issue with the required translations for the currently supported languages

2023-02-01 17:11 UTC, karynemayer requested changes
https://github.com/telosnetwork/teloscan/issues/348

Due to this issue being introduced in this sprint, I'm considering it a release blocker.

2023-02-02 20:48 UTC, donnyquixotic commented
> #348
> 
> Due to this issue being introduced in this sprint, I'm considering it a release blocker.

@karynemayer I can't reproduce?

2023-02-02 21:17 UTC, karynemayer commented
@donnyquixotic I can't reproduce it after a metamask update, so I closed the issue and I'll be executing the release

2023-02-02 21:18 UTC, karynemayer approved these changes

2023-02-02 21:18 UTC, merged