106 global transaction watcher toast notifications
telosnetwork/teloscan pull request #466
Opened 2023-10-25 18:07 UTC by Viterbo

# Fixes #106

## Description
This PR includes a packed solution to simplify the task of notifying the user whenever a transaction is signed and sent, succeeded or not, with a simple call to a generic signCustomTransaction function.

## Test scenarios

## Screen captures

[Notifications-on-Teloscan.webm](https://github.com/telosnetwork/teloscan/assets/4420760/9ba2dfec-a07c-49c2-b8d3-bc4fcbb07cb2)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2023-10-25 20:08 UTC, ezra-sg submitted a review, later dismissed
awesome job, works great 💯

2023-10-25 21:07 UTC, donnyquixotic requested changes

2023-10-25 21:07 UTC, donnyquixotic commented on src/antelope/mocks/AntelopeConfig.ts
> +    wrapError(description: string, error: unknown): AntelopeError {
rename to `transactionError` (I updated this in telos-wallet as part of the nft transfer PR)

2023-10-25 21:07 UTC, donnyquixotic commented on src/antelope/mocks/AccountStore.ts
> +            const trxError = ant.config.wrapError(actionError, error);
rename `wrapError` to `transactionError` see feedback in AntelopeConfig.ts

2023-10-25 21:09 UTC, donnyquixotic commented
@Viterbo is there a reason why all the new store files are added under the 'mocks' dir instead of 'store'?

2023-10-25 21:22 UTC, Viterbo commented
> @Viterbo is there a reason why all the new store files are added under the 'mocks' dir instead of 'store'?

Yes. It's because they are mocks :laughing: 
No, out of joke, those clases are not the actual Stores. They are just simplifyed and adapted version of the same Store-API we have in the real Antelope code (back in telos-wallet repo).

Why did I do that? because otherwise I would need to migrate the whole library and that would be an enormous effort too early. The job needs to be done but not now, rather after the lib is finished

2023-10-25 21:42 UTC, donnyquixotic submitted a review, later dismissed

2023-10-26 20:14 UTC, donnyquixotic approved these changes

2023-10-26 20:15 UTC, merged