380 csv export
telosnetwork/teloscan pull request #517
Opened 2024-01-29 19:27 UTC by ezra-sg

# Fixes #issue_number

## Description

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2024-01-29 19:31 UTC, ezra-sg commented on src/boot/errorHandling.js
> +export function useNotifications() {
expose notification functions as composable for use in script setup

2024-01-29 19:31 UTC, ezra-sg commented on src/boot/i18n.js
> +    legacy: false,
fix issue when using i18n as a composable

2024-01-29 22:44 UTC, ezra-sg commented on .eslintrc.js
> -        'max-len': ['error', { 'code': 120 }],
this was just annoying haha

2024-02-29 05:10 UTC, Viterbo approved these changes
Excellent work! 
Just a few minor changes, all related to the word "deposit" being translated into Latin-rooted languages.

2024-02-29 05:10 UTC, Viterbo commented on src/i18n/pt-br/index.js
> +            deposit: 'depósito',
```suggestion
            deposit: 'depositar',
```

2024-02-29 05:10 UTC, Viterbo commented on src/i18n/fr-fr/index.js
> +            deposit: 'dépôt',
```suggestion
            deposit: 'déposer',
```

2024-04-10 07:10 UTC, donnyquixotic requested changes
Default output is 100 records

2024-04-17 06:19 UTC, Viterbo commented
## Options

# Option 1
![image](https://github.com/telosnetwork/teloscan/assets/4420760/7866027d-3d74-47d6-9d10-e9458c45423e)

2024-04-25 01:45 UTC, Viterbo commented
@tomtomcrypto 

I added the new export API and it works really fast!!! 🔥 🔥 

However, I cannot request a range by timestamp, time, or date. I always get a code 500.
Can you check if I am doing something wrong here?
https://api.testnet.teloscan.io/export/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a/transactions/csv?captcha=10000000-aaaa-bbbb-cccc-000000000001&limit=10000&startTimestamp=1709262000000&endTimestamp=1709348400000

2024-04-25 14:35 UTC, tomtomcrypto commented
> @tomtomcrypto
> 
> I added the new export API and it works really fast!!! 🔥 🔥
> 
> However, I cannot request a range by timestamp, time, or date. I always get a code 500. Can you check if I am doing something wrong here? https://api.testnet.teloscan.io/export/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a/transactions/csv?captcha=10000000-aaaa-bbbb-cccc-000000000001&limit=10000&startTimestamp=1709262000000&endTimestamp=1709348400000

Looking into it

2024-04-26 17:23 UTC, pmjanus commented
I have a couple of changes I'd like to make to the export functionality:

Please adjust the width of the input boxes for selecting the export type (Transactions, Internal Transactions, Token Transfers, etc.). They currently appear too wide, and I'd like them to be narrower to take up less horizontal space.
Regarding the calendar control for selecting the date range, I'd like to change it from a single control that allows selecting a range to two separate controls. Please replace the current range selector with two individual calendar controls:

One calendar control should be used for selecting the start date
The other calendar control should be used for selecting the end date

This will allow users to choose the start and end dates independently,.

2024-05-13 16:57 UTC, pmjanus commented
We are missing the CSV Export option on the More section of the Navbar. (not on Advanced as it says on the PR).

2024-05-14 09:56 UTC, rozzaswap commented
@Viterbo Block number filtering doesn't seem to be working properly for me. I filtered from block 277737852 to 297737852

<img width="1143" alt="image" src="https://github.com/telosnetwork/teloscan/assets/105747830/abfbc5f3-a4e8-4161-ab32-b60e530bde8d">

After downloading the csv, blocks are shown from block 218418469 to 289651935

<img width="169" alt="image" src="https://github.com/telosnetwork/teloscan/assets/105747830/6f5e50e0-5317-47ef-bcfe-561d27755799">

2024-06-07 13:51 UTC, rozzaswap commented
@Viterbo the block filter fix has been deployed.

2024-06-17 14:54 UTC, rozzaswap commented
@Viterbo currently investigating why date filtering now not working:

<img width="501" alt="image" src="https://github.com/telosnetwork/teloscan/assets/105747830/9209d14d-62fe-4648-a857-60d0e67ad3bd">

2024-06-23 16:12 UTC, pmjanus commented
Getting an error on this:
<img width="1217" alt="image" src="https://github.com/telosnetwork/teloscan/assets/97489909/10c569b1-8186-45ee-b043-f8a571ae9323">

URL: https://deploy-preview-517--dev-mainnet-teloscan.netlify.app/export?type=erc20Transfers&account=0x5a35282125647253afd8af1a43bcde757bc10b3b

{
    "message": "Request failed.",
    "url": "http://api.teloscan.io/export/0x5a35282125647253afd8af1a43bcde757bc10b3b/transfers?captcha=P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hadwYXNza2V5xQVmwoDpB_cNWU2J9d8aCnd053Mzoq-shmapvrzsYItVetHEO9kPx6pxHGa5VgBlz-yKyDq26uAEAnWXjP2wB9wA4fWzNpimJb6piNCIrXff-XEmlGluaJwhU7P75VOaFFKTbLwaLaPY-zNFyHmmA7nuo-NEMMYL9FmZb6KU7tyV160Yiux4npXb-rXYqUEjuY0Ltmxp1UrQ4VuzxSHjTFvn7gFDyzPpYEjEtMDaYc2Z8fKDfjfk-Ihix1Zgq5Gw-5Q1abMY1bezPZqVtIpeJ-oa_rvkBabMQyY6-muKJHfRGtYVpD3Yx8XuYLebYO3uwqwkiFoFE6uF8DZw98C49RZImjxuIvO0QtWZuxc6m6XNro6bX8gHbpKloOZhn9IWhaTavfQ_QyZ9D5nm40C50Ff7f-6CH7J_KrOk3nkpWFZoKsu2qNUUc7CmJvL1saJumWug69pmy9xJIg9sQGlciAqdZp5uq8JiApcywnQVWC2RIYF4oPOi1pk_Kd2q4_EZ-BgiTfvnsWVDnfpxq9DlULX5_4t8u8ty-E_9wyeJKJjVL_2676JGNCIl8xC7FEZSCw2X44oiI32ShV9RyFm5LnzOECO6AXR70fSXV0FcHTRtFwa1ROi6v5ZEkKAzgpeRYqHSNTnAtEv3qikvgv4ZLkaEPUhxQIcUlkADbICVQS2wjHqgWtxd1nLqHyCYfinJoJrmsOcdYhHr5VF8cTT-QNG-Nl4VphyBW7qdKSIV-mcNE-92xgHIoQSzzWA7m9dHqQLNjCY8KuNYKNidEb4YzXz1D361RaLp34csnFJuwR6ScmyaODFpVz28Phpv6ttrXY226BMwNaSYOioy1oksLN3oIOSiyKzWZOgM3CmkoKr1UbGLeuXImvWiFMDjnCBMZC4MRQtlY1S3VmUY5TqdLWvzexc3YjTxs678avUR4m4iQVu11SHhyJRZwjwLcPXgHUok_b1w9SSkkZElXX_--nAijLg7lLFnPaYqsANRLK3x16b8KtucpT241408BRLnbcBcmVtswhsXa9mG4d-c9dud6e4zRuXU74iP6qTbtSlF3xp6EfbD6qhAcfvu17kRzdrpf9svnZ5RmawCotbt09e4OZyRhOElg4MVZefxESstwmsHHJun-3o-Cp1OYyqTjXiiiTaccXQBTcm243MtYVCuIMmKZK-Wizpvwl_WTyC_lete3WtU8Ld3iSvjQayGsS_ciksMuHSvVs6QL-EdIjhQw92L4-2-uf4P_bvoNFYttSLyRs8DhI-XM0GZwZdbgdr8FL0fkRamUDYRs-kVnFPZLlucDVUdLSHIt1H0Z6ur38aUKM0rubZHF0aZalwp4H-77Pv6t-6cKJ7LRMMFMSNheeDFOgrhEEdiQqpJTFtnj1AwMRcWMY-JXLxDpbJecu7XRVobB4eha2gqqqlOWOXfU011HkKYXW1Bsmr7hZNdovfehEokryV9_N89b553Y-WK4mBKGoj1f9GWPZRKhB2aeQLskVTJccsYVwFi8g9pmr3EMAWGR6GEA4ZY1S0LzPtnBzBuZ9tVfXh24tSURyHWSEYjRyDFiNqSf99XbYa8anlb24DU8pLVcxBgispLYlhX2yr8MdYUSvqS2viweiOW0_vuZEjPhcMw09AiXLGwBi5YUnH58u3E-qaz0UGSxp1jzG6F0NIl2ELNKbvDCv7R2f0QG42I4GXFmuwg_vUpLeHoQB7FQk0b1nRKzfW7KDEBe5dZD8erS89vy4n2wv3f1H_fVqGrh6Q3lAYEsw9o-sluIzzXv9xlTlvU47_y6oYRJsioU59YZuLy0tE1YatAcaqm1EFQcqozMTleASWf7nEsR48TbJyjZXhwzmZ4SSGoc2hhcmRfaWTOMa1MgaJrcqgxYzYxMzgwOKJwZAA.JWWJA2VCT7yvwiQOODoheLRn9BSIKLvrMIflj3Q1hMs&limit=10000&types=erc20&startTimestamp=1687233600000&endTimestamp=1688097600000&startDate=1687233600000&endDate=1688097600000&startTime=1687233600000&endTime=1688097600000",
    "status": "500"
}

2024-06-24 13:35 UTC, rozzaswap commented
Waiting for @tomtomcrypto to take a look at https://github.com/telosnetwork/teloscan-indexer/issues/255

2024-07-19 13:51 UTC, Viterbo commented
Tested with ERC transactions and date range. Ready for final test and merge

2024-07-19 14:33 UTC, pmjanus commented
There are issues with date and block validations:
Dates:
You can set an end date that is previous to the start date.

Nitpick since who would input negative block - Blocks:
You can set negative blocks, Download CSV button is disabled but theres no indication that the block field is the issue.

2024-07-19 21:17 UTC, merged