#552 | Redesign Transaction Page
telosnetwork/teloscan pull request #562
Opened 2024-03-12 13:07 UTC by Viterbo

# Fixes #552

## Description

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2024-03-12 23:59 UTC, donnyquixotic requested changes

2024-03-12 23:59 UTC, donnyquixotic commented on src/components/GasLimitAndUsage.vue
> +// import { useI18n } from 'vue-i18n';
```suggestion
```

2024-03-12 23:59 UTC, donnyquixotic commented on src/components/GasLimitAndUsage.vue
> +// const { t: $t } = useI18n();
```suggestion
```

2024-03-12 23:59 UTC, donnyquixotic commented on src/components/GasLimitAndUsage.vue
> +</style>
```suggestion
```
can remove empty class

2024-03-12 23:59 UTC, donnyquixotic commented on src/components/MethodField.vue
> +    } else if (!props.trx.parsedTransaction && props.trx.input === '0x' && propValue.value) {
we reference `0x` here and `0x0` on line 63, are these handling distinct cases or can we use `ZERO_ADDRESSES` for these?

2024-03-12 23:59 UTC, donnyquixotic commented on src/types/Evm
can remove empty file

2024-03-13 00:05 UTC, donnyquixotic commented
@Viterbo Can you fix the footer anchoring for the tx page?

2024-03-13 14:41 UTC, Viterbo commented
> @Viterbo Can you fix the footer anchoring for the tx page?

That code was written by @ezra-sg and is correct. Look at the answer from the indexer:
![image](https://github.com/telosnetwork/teloscan/assets/4420760/d084251b-2d6a-487a-9448-d046fd292908)

2024-03-13 19:24 UTC, donnyquixotic approved these changes

2024-03-13 22:32 UTC, donnyquixotic approved these changes

2024-03-14 16:01 UTC, merged