#565 - Teloscan homepage - Global Layout
telosnetwork/teloscan pull request #566
Opened 2024-03-15 21:20 UTC by Viterbo

# Fixes #565

## Description

## Test scenarios

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [x] I have added appropriate test coverage

2024-03-15 23:25 UTC, donnyquixotic requested changes
Great Job! minor feedback

2024-03-15 23:25 UTC, donnyquixotic commented on src/lib/utils.js
> +    // tenemos que agregar una cantidad de ceros igual a displayDecimals
comentarios en inglés por favor

2024-03-15 23:25 UTC, donnyquixotic commented on src/css/global/_global.scss
empty file?

2024-03-18 13:10 UTC, Viterbo commented on src/lib/utils.js
> +    // tenemos que agregar una cantidad de ceros igual a displayDecimals
nuuuuuuuuu :see_no_evil:

2024-03-18 15:06 UTC, donnyquixotic approved these changes

2024-03-22 15:52 UTC, closed without merging